/**
 * exporter.js — Export to JSON, Godot .tres, GDScript
 */

const ExporterModule = (() => {

  function toJSON(project) {
    return JSON.stringify(project, null, 2);
  }

  function toTRES(project) {
    const layout = project.layout;
    const imageRelPath = project.spritesheet || 'res://assets/sprites/spritesheet.png';

    // Build explicit regions if not a pure grid
    const hasExplicit = project.sprites.some(s => s.blockIndex === -1);
    const typeEnum = hasExplicit ? 2 : (layout.type === 'NESTED_GRID' ? 1 : 0);

    let out = `; SpriteSheetLayout — Generated by SlopEditor v1.0\n`;
    out += `; Project: ${project.name}\n\n`;
    out += `[gd_resource type="Resource" script_class="SpriteSheetLayout" load_steps=3 format=3]\n\n`;
    out += `[ext_resource type="Script" path="res://core/resources/sprite_sheet_layout.gd" id="1_script"]\n`;
    out += `[ext_resource type="Texture2D" path="${imageRelPath}" id="2_texture"]\n\n`;
    out += `[resource]\n`;
    out += `script = ExtResource("1_script")\n`;
    out += `texture = ExtResource("2_texture")\n`;
    out += `type = ${typeEnum}\n`;
    out += `columns = ${layout.columns}\n`;
    out += `rows = ${layout.rows}\n`;
    if (layout.type === 'NESTED_GRID') {
      out += `sub_columns = ${layout.sub_columns}\n`;
      out += `sub_rows = ${layout.sub_rows}\n`;
    }
    out += `regions = {}\n`;
    out += `\n`;
    out += `; ── Sprites Defined ──────────────────────────────────\n`;
    project.sprites.forEach(sp => {
      out += `; "${sp.name}" → block:${sp.blockIndex} region:[${sp.region.x}, ${sp.region.y}, ${sp.region.w}, ${sp.region.h}]\n`;
    });
    if (project.animations.length > 0) {
      out += `\n; ── Animations ───────────────────────────────────────\n`;
      project.animations.forEach(anim => {
        const frameIds = anim.frames.map(f => `${f.sprite_id}[${f.sub_index ?? 0}]`).join(', ');
        out += `; "${anim.name}" fps:${anim.fps} loop:${anim.loop} frames:[${frameIds}]\n`;
      });
    }
    return out;
  }

  function toGDScript(project) {
    const name = (project.name || 'SpriteSheet').replace(/[^a-zA-Z0-9_]/g, '_').toUpperCase();
    let out = `# SpriteSheet Constants — Generated by SlopEditor v1.0\n`;
    out += `# Project: ${project.name}\n`;
    out += `# Paste this inside your script or as a global autoload\n\n`;
    out += `class_name ${name}_Constants\n\n`;

    if (project.spritesheet) {
      out += `const SPRITESHEET_PATH = "${project.spritesheet}"\n\n`;
    }

    out += `# ── Sprite Regions ────────────────────────────────────\n`;
    project.sprites.forEach(sp => {
      const constName = sp.name.toUpperCase().replace(/[^A-Z0-9]/g, '_');
      out += `const SPRITE_${constName} = Rect2(${sp.region.x}, ${sp.region.y}, ${sp.region.w}, ${sp.region.h})\n`;
    });

    if (project.animations.length > 0) {
      out += `\n# ── Animations ───────────────────────────────────────\n`;
      project.animations.forEach(anim => {
        const constName = anim.name.toUpperCase().replace(/[^A-Z0-9]/g, '_');
        const spriteRefs = anim.frames.map(f => {
          const sp = project.sprites.find(s => s.id === f.sprite_id);
          const sName = sp ? `SPRITE_${sp.name.toUpperCase().replace(/[^A-Z0-9]/g, '_')}` : 'null';
          return sName;
        });
        out += `const ANIM_${constName}_FRAMES = [${spriteRefs.join(', ')}]\n`;
        out += `const ANIM_${constName}_FPS = ${anim.fps}\n`;
        out += `const ANIM_${constName}_LOOP = ${anim.loop}\n`;
      });
    }

    out += `\n# ── Helper ────────────────────────────────────────────\n`;
    out += `static func get_atlas(sprite_const: Rect2, texture: Texture2D) -> AtlasTexture:\n`;
    out += `\tvar atlas = AtlasTexture.new()\n`;
    out += `\tatlas.atlas = texture\n`;
    out += `\tatlas.region = sprite_const\n`;
    out += `\treturn atlas\n`;

    return out;
  }

  function download(filename, content) {
    const blob = new Blob([content], { type: 'text/plain' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = filename;
    a.click();
    URL.revokeObjectURL(a.href);
  }

  return { toJSON, toTRES, toGDScript, download };
})();
